# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

def cCLOAlbum
    [
    "Core",
    ]
end
def cCLOCommon
    [
    "Core",
    ]
end

def cPodsDebugX
    
    pod "CLOCommon", :path=>'../../../ccloveobjc/CLOCommon', :subspecs => cCLOCommon
    
end
def cPodsReleaseX
    
    pod "CLOCommon", :git=>'https://github.com/ccloveobjc/CLOCommon.git', :subspecs => cCLOCommon
    
end

target 'iRemeber' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  inhibit_all_warnings!

  # Pods for iRemeber
  cPodsDebugX
  
  pod 'Bugly'
  pod 'WCDB'

end
